services:
  docker1:
    image: pallavimarni/a_1:docker1
    ports:
      - 6000:6000
    volumes:
      - .:/app
    networks:
      - my-network

  docker2:
    image: pallavimarni/a_1:docker2
    ports:
      - 6001:6001
    volumes:
      - .:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
