apiVersion: v1
kind: Service
metadata:
  name: docker-2-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: docker-2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001