apiVersion: v1
kind: Service
metadata:
  name: docker-1-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: docker-1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000